/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qldatphongks;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import qldatphongks.Form.Dangkidv_form;
import qldatphongks.Form.Dangkitn_form;
import qldatphongks.Form.Datphong_form;
import qldatphongks.Form.Dichvu_form;
import qldatphongks.Form.Hoadon_form;
import qldatphongks.Form.Khachhang_form;
import qldatphongks.Form.Loaiphong_form;
import qldatphongks.Form.Phong_form;
import qldatphongks.Form.Tiennghi_form;

/**
 *
 * @author Admin
 */
public class Menuform extends javax.swing.JFrame {

    /**
     * Creates new form Menuform
     */
    public Menuform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnphong = new javax.swing.JButton();
        btndapphong = new javax.swing.JButton();
        btnlp = new javax.swing.JButton();
        btnkh = new javax.swing.JButton();
        btntn = new javax.swing.JButton();
        btndv = new javax.swing.JButton();
        btndkdv = new javax.swing.JButton();
        btndktn = new javax.swing.JButton();
        btnhd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnthoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BẢNG QUẢN LÝ ĐẶT PHÒNG KHÁCH SẠN");

        btnphong.setBackground(new java.awt.Color(204, 204, 204));
        btnphong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnphong.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\12.PNG")); // NOI18N
        btnphong.setText("Phòng");
        btnphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphongActionPerformed(evt);
            }
        });

        btndapphong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndapphong.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\5.PNG")); // NOI18N
        btndapphong.setText("Đặt phòng");
        btndapphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndapphongActionPerformed(evt);
            }
        });

        btnlp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlp.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\9.PNG")); // NOI18N
        btnlp.setText("Loại phòng");
        btnlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlpActionPerformed(evt);
            }
        });

        btnkh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnkh.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\4.PNG")); // NOI18N
        btnkh.setText("Khách hàng");
        btnkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhActionPerformed(evt);
            }
        });

        btntn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btntn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\11.PNG")); // NOI18N
        btntn.setText("Tiện nghi");
        btntn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntnActionPerformed(evt);
            }
        });

        btndv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndv.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\2.PNG")); // NOI18N
        btndv.setText("Dịch vụ");
        btndv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndvActionPerformed(evt);
            }
        });

        btndkdv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndkdv.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\7.PNG")); // NOI18N
        btndkdv.setText("Đăng kí dịch vụ");
        btndkdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndkdvActionPerformed(evt);
            }
        });

        btndktn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndktn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\8.PNG")); // NOI18N
        btndktn.setText("Đăng kí tiện nghi");
        btndktn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndktnActionPerformed(evt);
            }
        });

        btnhd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\6.PNG")); // NOI18N
        btnhd.setText("Hóa đơn");
        btnhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐẶT PHÒNG KHÁCH SẠN");

        btnthoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnthoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\16.PNG")); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\1.PNG")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnphong, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnkh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndkdv, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndapphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndktn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlp, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(btnhd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnthoat)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnphong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndapphong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnkh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndkdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnhd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndktn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnthoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphongActionPerformed
        // TODO add your handling code here:
        Phong_form phf = new Phong_form();
        phf.setVisible(true);
        phf.pack();
        phf.setLocationRelativeTo(null);
        phf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnphongActionPerformed

    private void btndapphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndapphongActionPerformed
        // TODO add your handling code here:
        Datphong_form dphf = new Datphong_form();
        dphf.setVisible(true);
        dphf.pack();
        dphf.setLocationRelativeTo(null);
        dphf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btndapphongActionPerformed

    private void btnlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlpActionPerformed
        // TODO add your handling code here:
        Loaiphong_form lphf = new Loaiphong_form();
        lphf.setVisible(true);
        lphf.pack();
        lphf.setLocationRelativeTo(null);
        lphf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnlpActionPerformed

    private void btnkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhActionPerformed
        // TODO add your handling code here:
        Khachhang_form kh = new Khachhang_form();
        kh.setVisible(true);
        kh.pack();
        kh.setLocationRelativeTo(null);
        kh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnkhActionPerformed

    private void btntnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntnActionPerformed
        // TODO add your handling code here:
        Tiennghi_form tn = new Tiennghi_form();
        tn.setVisible(true);
        tn.pack();
        tn.setLocationRelativeTo(null);
        tn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btntnActionPerformed

    private void btndvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndvActionPerformed
        // TODO add your handling code here:
        Dichvu_form dv = new Dichvu_form();
        dv.setVisible(true);
        dv.pack();
        dv.setLocationRelativeTo(null);
        dv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btndvActionPerformed

    private void btndkdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndkdvActionPerformed
        // TODO add your handling code here:
        Dangkidv_form dkdv = new Dangkidv_form();
        dkdv.setVisible(true);
        dkdv.pack();
        dkdv.setLocationRelativeTo(null);
        dkdv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btndkdvActionPerformed

    private void btndktnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndktnActionPerformed
        // TODO add your handling code here:
        Dangkitn_form dktn = new Dangkitn_form();
        dktn.setVisible(true);
        dktn.pack();
        dktn.setLocationRelativeTo(null);
        dktn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btndktnActionPerformed

    private void btnhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhdActionPerformed
        // TODO add your handling code here:
        Hoadon_form hd = new Hoadon_form();
        hd.setVisible(true);
        hd.pack();
        hd.setLocationRelativeTo(null);
        hd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnhdActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
         btnthoat.setToolTipText("Ấn thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát bảng"
                + " Menu", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_btnthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menuform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndapphong;
    private javax.swing.JButton btndkdv;
    private javax.swing.JButton btndktn;
    private javax.swing.JButton btndv;
    private javax.swing.JButton btnhd;
    private javax.swing.JButton btnkh;
    private javax.swing.JButton btnlp;
    private javax.swing.JButton btnphong;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btntn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
