/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qldatphongks.Form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static qldatphongks.Connection.getConnection;
import qldatphongks.Loaiphong;

/**
 *
 * @author Admin
 */
public final class Loaiphong_form extends javax.swing.JFrame {

    /**
     * Creates new form Loaiphong_form
     */
    public Loaiphong_form() {
        initComponents();
        getConnection();
        hienThiDanhSachLoaiphong();
    }
    Connection con = null;
    Statement st = null;

    public ArrayList<Loaiphong> layDanhSachLoaiphong() {
        ArrayList<Loaiphong> dslp = new ArrayList<>();
        Connection con = getConnection();
        try {
            st = (Statement) con.createStatement();
            String sql = "SELECT * FROM Loaiphong";
            // Thực thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            Loaiphong lp;
            while (rs.next()) {
                lp = new Loaiphong(rs.getString("Maloai"), rs.getString("Tenloai"), rs.getDouble("Gialoai"));

                //Thêm vào danh sách
                dslp.add(lp);
            }
        } catch (SQLException ex) {
        }
        return dslp;
    }

    public void hienThiDanhSachLoaiphong() {
        String colTieuDe1[] = new String[]{"Mã loại phòng", "Tên loại phòng", "Giá loại phòng"};
        ArrayList<Loaiphong> dslp = layDanhSachLoaiphong();

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dslp.size(); i++) {

            row = new Object[3];

            // GÃ�N GIÃ� TRá»Š
            row[0] = dslp.get(i).getMaloai();
            row[1] = dslp.get(i).getTenloai();
            row[2] = dslp.get(i).getGialoai();

            model.addRow(row);
        }
        Tableloaiphong.setModel(model);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbloaiphong = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableloaiphong = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtmaloai = new javax.swing.JTextField();
        txttenloai = new javax.swing.JTextField();
        txtgialoai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnthemlph = new javax.swing.JButton();
        btnsualph = new javax.swing.JButton();
        btnxoalph = new javax.swing.JButton();
        btnnhaplailph = new javax.swing.JButton();
        btnthoatlph = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BẢNG LOẠI PHÒNG");

        lbloaiphong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbloaiphong.setText("LOẠI PHÒNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tableloaiphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại", "Giá loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tableloaiphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableloaiphongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tableloaiphong);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Mã loại");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Tên loại");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Giá loại");

        btnthemlph.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnthemlph.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\29.PNG")); // NOI18N
        btnthemlph.setText("Thêm");
        btnthemlph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemlphActionPerformed(evt);
            }
        });

        btnsualph.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsualph.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\24.PNG")); // NOI18N
        btnsualph.setText("Sửa");
        btnsualph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsualphActionPerformed(evt);
            }
        });

        btnxoalph.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnxoalph.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\26.PNG")); // NOI18N
        btnxoalph.setText("Xóa");
        btnxoalph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoalphActionPerformed(evt);
            }
        });

        btnnhaplailph.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnnhaplailph.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\27.PNG")); // NOI18N
        btnnhaplailph.setText("Nhập lại");
        btnnhaplailph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhaplailphActionPerformed(evt);
            }
        });

        btnthoatlph.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnthoatlph.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\ks\\28.PNG")); // NOI18N
        btnthoatlph.setText("Thoát");
        btnthoatlph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatlphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnthemlph)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsualph)
                        .addGap(3, 3, 3)
                        .addComponent(btnxoalph)
                        .addGap(1, 1, 1)
                        .addComponent(btnnhaplailph)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnthoatlph))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtgialoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txttenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgialoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthemlph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsualph, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btnxoalph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnhaplailph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthoatlph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lbloaiphong))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lbloaiphong)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemlphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemlphActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection();
        try {
          
            st = (Statement) con.createStatement();
            String query = "INSERT INTO Loaiphong(Maloai,Tenloai, Gialoai) VALUES('" + txtmaloai.getText() + "',"
                    + "'" + txttenloai.getText() + "','" + txtgialoai.getText() + "')";

            st.execute(query);
            hienThiDanhSachLoaiphong();

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnthemlphActionPerformed

    private void btnsualphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsualphActionPerformed
        // TODO add your handling code here:
        if (Tableloaiphong.getSelectedRow() == -1) {
            if (Tableloaiphong.getRowCount() == 0) {
               lbloaiphong.setText("Table is empty");
            } else {
                 lbloaiphong.setText("You must choose a service");
            }
        } else {
            DefaultTableModel model = (DefaultTableModel) Tableloaiphong.getModel();
            model.setValueAt(txtmaloai.getText(), Tableloaiphong.getSelectedRow(), 0);
            model.setValueAt(txttenloai.getText(), Tableloaiphong.getSelectedRow(), 1);
            model.setValueAt(txtgialoai.getText(), Tableloaiphong.getSelectedRow(), 2);
            
        }
    }//GEN-LAST:event_btnsualphActionPerformed

    private void btnxoalphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoalphActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection();
        try {
            
            st = (Statement) con.createStatement();
            String query = "DELETE FROM Loaiphong WHERE Maloai = '" + txtmaloai.getText() + "'";
            st.executeUpdate(query);
            hienThiDanhSachLoaiphong();

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnxoalphActionPerformed

    private void btnnhaplailphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhaplailphActionPerformed
        // TODO add your handling code here:
        txtmaloai.setText("");
        txttenloai.setText("");
        txtgialoai.setText("");
        txtmaloai.requestFocus();
    }//GEN-LAST:event_btnnhaplailphActionPerformed

    private void btnthoatlphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatlphActionPerformed
        // TODO add your handling code here:
        btnthoatlph.setToolTipText("Ấn thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát bảng"
                + " loại phòng", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_btnthoatlphActionPerformed

    private void TableloaiphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableloaiphongMouseClicked
        // TODO add your handling code here:
        int i = Tableloaiphong.getSelectedRow();
        TableModel model = Tableloaiphong.getModel();
        txtmaloai.setText(model.getValueAt(i, 0).toString());
        txttenloai.setText(model.getValueAt(i, 1).toString());
        txtgialoai.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_TableloaiphongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loaiphong_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loaiphong_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loaiphong_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loaiphong_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Loaiphong_form().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tableloaiphong;
    private javax.swing.JButton btnnhaplailph;
    private javax.swing.JButton btnsualph;
    private javax.swing.JButton btnthemlph;
    private javax.swing.JButton btnthoatlph;
    private javax.swing.JButton btnxoalph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbloaiphong;
    private javax.swing.JTextField txtgialoai;
    private javax.swing.JTextField txtmaloai;
    private javax.swing.JTextField txttenloai;
    // End of variables declaration//GEN-END:variables

   
}
